const MENU = {
  INTRO: 'intro',
  MEMBERS: 'members',
  MEMBER: 'member',
  BOARDS: 'boards',
  BOARD: 'board',
  POST: 'post',
  PROJECTS: 'projects',
  PROJECT: 'project',
  ACTIVITIES: 'activities',
  ACTIVITY: 'activity',
  BOOKS: 'books',
  BOOK: 'book',
  APPLY: 'apply',
  ADMIN: 'admin',
  MYINFO: 'my-info',
  PASSWORD: 'password',
  RESET_PASSWORD: 'reset',
  SIGNIN: 'login',
  SIGNUP: 'register',
  FORBIDDEN: 'forbidden',
  NOT_FOUND: 'not-found',
  INTERVIEW_TIME: 'interview-time',
  NEW_BOARDS: 'new-boards',
  NEW_BOARD: 'new-board',
  MY_PAGE: 'my-page',
  MY_PAGE_MESSAGE_LIST: 'message-list',
  MY_PAGE_MESSAGE_FORM: 'message-form',
  MY_PAGE_BADGE_LIST: 'badge-list',
};

export { MENU };
