const MENU = {
    INTRO: 'intro',
    MEMBERS: 'members',
    MEMBER: 'member',
    BOARDS: 'boards',
    BOARD: 'board',
    POST: 'post',
    PROJECTS: 'projects',
    PROJECT: 'project',
    ACTIVITIES: 'activities',
    ACTIVITY: 'activity',
    BOOKS: 'books',
    BOOK: 'book',
    APPLY: 'apply',
    ADMIN: 'admin',
    MYINFO: 'my-info',
    PASSWORD: 'password',
    RESET_PASSWORD: 'reset',
    SIGNIN: 'login',
    SIGNUP: 'register',
    FORBIDDEN: 'forbidden',
    NOT_FOUND: 'not-found',
    INTERVIEW_TIME: 'interview-time',
};

export { MENU };