export const MEMBER_ROLE = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  GRADUATED: 'GRADUATED',
  COMPLETE: 'COMPLETE',
  INACTIVE: 'INACTIVE',
  MEMBER: 'MEMBER',
  UNACCEPTED: 'UNACCEPTED',
  EXPELLED: 'EXPELLED',
  QUIT: 'QUIT',
  PUBLIC: 'PHUBLIC',
};

export const UNAUTHORIZED_MEMBER_ROLES = [
  MEMBER_ROLE.UNACCEPTED,
  MEMBER_ROLE.EXPELLED,
  MEMBER_ROLE.QUIT,
  MEMBER_ROLE.PUBLIC,
];

export const ADMIN_MEMBER_ROLES = [MEMBER_ROLE.ADMIN, MEMBER_ROLE.SUPER_ADMIN];
