const MENU = {
  INTRO: 'intro',
  MEMBERS: 'members',
  MEMBER: 'member',
  POST: 'post',
  PROJECTS: 'projects',
  PROJECT: 'project',
  ACTIVITIES: 'activities',
  ACTIVITY: 'activity',
  BOOKS: 'books',
  BOOK: 'book',
  APPLY: 'apply',
  ADMIN: 'admin',
  MYINFO: 'my-info',
  PASSWORD: 'password',
  RESET_PASSWORD: 'reset',
  SIGNIN: 'login',
  SIGNUP: 'register',
  FORBIDDEN: 'forbidden',
  NOT_FOUND: 'not-found',
  INTERVIEW_TIME: 'interview-time',
  BOARD: 'board',
  MY_PAGE: 'my-page',
  MY_PAGE_BADGE_LIST: 'badge-list',
  MESSAGE_LIST: 'message-list',
  MESSAGE_FORM: 'message-form',
  MESSAGE_ALL_LIST: 'message-all-list',
};

export { MENU };
